name: better_player_plus
version: 1.1.2
homepage: https://github.com/SunnatilloShavkatov/betterplayer.git
documentation: https://github.com/SunnatilloShavkatov/betterplayer.git
description: "Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run."

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.19.1
  wakelock_plus: ^1.4.0
  path_provider: ^2.1.5
  visibility_detector: ^0.4.0+2
  flutter_widget_from_html_core: ^0.17.0
  marquee: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: uz.shs.better_player_plus
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin
